### PR TITLE
Create Worksheet 3A

### PR DESCRIPTION
**Pull request by sciclic**
Here is Worksheet 3A, some notes:

+ Following today's teaching team meeting, I have cut down on some content - there are a total of 11 *autograded* questions, one extra non-autograded practice question at the end of the ggplot section of the worksheet, and two non-autograded tasks within the dplyr section of the worksheet. Let me know what you think! If it seems too short now I can add a few more exercises, I'm not sure of how long it will take.

+ Didn't ask at the meeting today, but given that team ASDA is now working on the worksheets (and will hopefully implement the autograder for this worksheet), should the content of the worksheet (i.e. this pull request) be reviewed before or after they implement the autograder? I'm thinking before in case adjustments need to be made?

Thank you!

### CODE REVIEW

**Comment by dy-lin** [comment]
@sciclic aren't we doing worksheet dev on https://github.com/UBC-STAT/stat-545-instructor?

**Comment by dy-lin** [comment]
I've implemented the empty code cell as it was implemented for worksheet04a.

**Comment by sciclic** [comment]
Thank you @dy-lin, just opened a pull request with this same worksheet in the right repo (sorry again) - I think we should close this push request and delete the file from this repo?

**Comment by wvictor14** [comment]
Yeah the concern is just other students seeing the solutions. Probably best to just delete the whole branch here so it isn't in the history?

**Pull request closed without merging**
