### PR TITLE
finish lecture-worksheet-1

### PR DESCRIPTION
**Pull request by sciclic**
I have completed section 2 of this worksheet (corresponding to Class 3 - R Markdown).

- To approach the issue of **how to guide students through practicing R Markdown in RStudio, while still using the worksheet**, there are two components to section 2: (1) Answer a few autograded questions in quiz form, and (2) Open the worksheet document in .Rmd form (which we will provide to students through Canvas) in RStudio, and follow the instructions for the second activity, which is adapted from last year's STAT545 guidebook content, and won't be autograded, which I don't think is a problem since this worksheet is optional.

- Based on your comments about **nbGrader** on my last push request (#30), I have adapted the content that I had written thus far to a format more appropriate for nbGrader that is hopefully easier for Team Sonja. Thanks again for clarifying that!

- In addition, I have added "An important note" section to remind students that submission of this worksheet is optional, an "Attributions" section to credit inspiration for the worksheet's contents, and an **"Instructions + Grading"** section. About the latter, I don't know if adding it to this first worksheet is confusing and it's better to just put up the instructions overall elsewhere, or have them both elsewhere (somewhere in the website / canvas?) and at the start of every worksheet. I did clarify that students should keep in mind that this worksheet is still optional, but I'm still not sure if it's confusing to have them there altogether.

- I am also somewhat worried that the instructions about **opening the Rmd in RStudio** are not clear enough, but I'm not sure of how to make them better!

I look forward to hearing your feedback and I hope you like the *final* result! Thank you.

### CODE REVIEW

**Comment by sciclic** [comment]
Oh no! I apologize, I just realized that in moving the lecture-worksheet-1.Rmd to a new folder ("worksheets") locally and pushing my changes, now it doesn't show the differences between the original and this updated version because it appears as a brand new document 😞  I'm so sorry, I'll remember not to move files until pull requests are resolved!

**Comment by vincenzocoia** [comment]
Thank you for this! This worksheet looks like a winner. There is still one more thing that needs changing before passing it on to Team Sonja: there should only be one "solution chunk" (not two), and there should be a "test chunk" that follows the solution chunk. For example, the following two code chunks currently follow Question 1.2:

```{r question-1-2}
answer1.2 <- #youranswer
```

```{r answer-1-2}
### BEGIN SOLUTION
answer1.2 <- 1
### END SOLUTION
```

Side note: the first code chunk will throw an error, which means that (I think) nbgrader won't be able to compile the student version of the worksheet.
 
These should be combined into one code chunk like so:

```{r question-1-2}
#answer1.2 <- youranswer
### BEGIN SOLUTION
answer1.2 <- 1
### END SOLUTION
```

Then, there should be another code chunk following, containing tests. It will eventually contain something like this:

```{r question-1-2-test}
test_that("Question 1.2", {
    expect_equal(digest(as.numeric(answer1.2)), "6717f2823d3202449301145073ab8719")
})
```

Notes about this choice of test:

- The function `digest::digest()` "encrypts" the object (in this case, the numeric `1`) into a unique hash, so that students don't see the answer (otherwise, they'd see something like `expect_equal(answer1.2, 1)`, and so would know that the answer is `1`. To come up with `"6717f2823d3202449301145073ab8719"`, I had to manually run `digest::digest(as.numeric(1))`.
- We have to be flexible with the type of object a student creates. It's possible (although unlikely) that a student provides an _integer_ as an answer -- `answer1.2 <- 1L` -- which gets `digest()`ed differently. Hence the `as.numeric()`.
 
I think we should see if Team Sonja can write the tests. We can prompt them with something like this:

```{r question-1-2-test}
# Test that students answer with 1
```

We'd also give them the above intel about `digest()` and being careful about not making the comparison too strict, and then provide feedback when they come up with a draft.

**Comment by sciclic** [comment]
Apologies as I just read this now after I wrote Worksheet 2 and I made the same mistakes! I will correct the chunks and add tests, I can try using digest myself but I may leave the tests for Team Sonja if you confirm that's okay (like you mentioned, adding comments with what should be tested). Thank you for the feedback!

**Comment by vincenzocoia** [comment]
> I may leave the tests for Team Sonja if you confirm that's okay

Certainly!

**Pull request merged**
