### PR TITLE
propose team leadership

### PR DESCRIPTION
**Pull request by vincenzocoia**
@UBC-STAT/stat545 Here is my proposed arrangement.

I'm trying for alternating between being a leader and a second reader. So, for example, a four-week cycle might look like:

- Week 1: Worksheet leader
- Week 2: Worksheet 2nd reader (and office hour)
- Week 3: Milestone leader
- Week 4: Milestone 2nd reader

STAT 545B is still TBD.

Also, I'm not flying out next week anymore. @wvictor14 if you're still up for following through with the lecture, I'll act as a moderator that day, and I'll take your review of Collaborative Milestone 3.

@wvictor14 @dy-lin @sciclic @almas2019 If this looks OK to you, please let me know.

### CODE REVIEW

**Comment by dy-lin** [comment]
Looks good to me, Vincenzo!

**Comment by sciclic** [comment]
Looks good to me!!

**Comment by wvictor14** [comment]
> @wvictor14 @dy-lin @sciclic @almas2019 If this looks OK to you, please let me know.
Sounds good

> Also, I'm not flying out next week anymore. @wvictor14 if you're still up for following through with the lecture, I'll act as a moderator that day, and I'll take your review of Collaborative Milestone 3.

I don't mind leading, or just regular TA'ing!

**Comment by almas2019** [comment]
Hi Vincenzo, looks fine to me.

**Comment by vincenzocoia** [comment]
Great! I'll update Asana.

**Pull request merged**
